feat: Support for renaming title of prompt(#279).
logancyang/obsidian-copilot pull request #631
Opened 2024-09-10 11:00 UTC by Emt-lin

Trying to address the problem that title of prompt can't change without altering the `CustomPrompt` structure.

I think the best solution is to change the `CustomPrompt` structure appropriately.

2024-09-10 21:26 UTC, logancyang commented
Seems you are updating an old version. The code you are changing no long exists, please pull the latest code.

2024-09-10 21:27 UTC, logancyang commented on src/main.ts
> -                    this.dbPrompts.put({
Seems you have an old version.

2024-09-10 21:28 UTC, logancyang requested changes
Seems you are updating an old version. The code you are changing no long exists, please pull the latest code.

2024-09-11 09:30 UTC, closed without merging

2024-09-11 09:34 UTC, Emt-lin commented
this PR is canceled.